name: Check Indicators for SPYTIPS COOL STRATEGY

on:
  schedule:
    # SELECT DAILY RUN TIME (UTC)
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yahooquery pandas yfinance

      - name: run script
        run: |
          python3 main.py

      - name: Read content from file
        id: read_file
        run: |
          if [[ -f message.txt ]]; then
            CONTENT=$(cat message.txt | sed ':a;N;$!ba;s/\n/\\n/g')
            echo "CONTENT=$CONTENT" >> $GITHUB_ENV
          else
            echo "File message.txt not found. No changes to commit."
            exit 0
          fi

      - name: Send notification to Discord
        env:
          CONTENT: ${{ env.CONTENT }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"${CONTENT}\"}" \
          $DISCORD_WEBHOOK_URL
      
      - name: Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add history*.txt
          git commit -m "Update current indicator data [ci skip]" || exit 0
          git push origin main || git push origin main --set-upstream
